version: "3.8"

x-app-variables: &app-variables
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_HOST=postgres
  - POSTGRES_DB=postgres

  - FLASK_APP=main.py
  - FLASK_RUN_HOST=0.0.0.0
  - FLASK_RUN_PORT=8015
  - FLASK_ENV=development

services:
  backend:
    build:
      context: .
    depends_on:
      - postgres
    environment: *app-variables
    volumes:
      - ./:/app
    ports:
      - "8015:8015"
    command: >
      bash -c "
      alembic upgrade head &&
      cd app &&
      flask run"

  postgres:
    image: postgres:12
    environment: *app-variables

volumes:
  postgres:
