"""Add models Staff, Staff, Order

Revision ID: 4f3363512f44
Revises: ad6d33995953
Create Date: 2021-11-24 11:55:24.715904

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4f3363512f44"
down_revision = "ad6d33995953"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staffs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "book_m2m_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("books_id", sa.Integer(), nullable=True),
        sa.Column("orders_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["books_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orders_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_m2m_order")
    op.drop_table("orders")
    op.drop_table("users")
    op.drop_table("staffs")
    # ### end Alembic commands ###
